[toolchain]
anchor_version = "0.31.1"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sol_arb_executor = "RoroSC7cukdtr1WFantguWKcZ9KTwqjnMRJYo9EcL51"

[programs.mainnet]
sol_arb_executor = "RoroSC7cukdtr1WFantguWKcZ9KTwqjnMRJYo9EcL51"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test:ts"
